contributor1-features
site_name: Documentation Programming Quotes quotes-docs-efrei-team

nav:
  - Home: index.md
  - Features: features.md
  - Core Functions: functions.md
  - User Interface: user-interface.md


theme:
  name: readthedocs

=======
site_name: Documentation Programming Quotes efrei-team
nav:
  - Home: index.md
<<<<<<< HEAD
  - User's Guide:
      - Features: features/features.md
      - Core Functions: features/functions.md
      - User Interface: features/user-interface.md
  - Logs:
      - Initiateur: logs/log-initiateur.md
      - Contributeur 1: logs/log-contributeur-1.md
      - Contributeur 2: logs/log-contributeur-2.md
      - Contributeur 3: logs/log-contributeur-3.md

theme: readthedocs
=======
  - Features: features.md
  contributor-logs
  - User Interface: user-interface.md
  - Logs:
      - Contributeur 1: logs/log-contributeur-1.md
      - Contributeur 3: logs/log-contributeur-3.md

=======
  - Core Functions: functions.md 
main
main
>>>>>>> 79584cfed393c0067aed6d43ac1fb1754bf0f038
